openapi: 3.0.0
info:
  title: FAQ API
  version: 1.0.0
  description: API to manage and query FAQs.

paths:
  /all_faqs:
    get:
      summary: Get all FAQs
      description: Retrieve a list of all FAQs
      responses:
        200:
          description: A list of FAQs
          content:
            application/json:
              schema:
                type: object
                properties:
                  faqs:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          example: 1
                        maincategory_ko:
                          type: string
                          example: 일반 질문
                        maincategory_en:
                          type: string
                          example: General Questions
                        subcategory_ko:
                          type: string
                          example: 가입 관련
                        subcategory_en:
                          type: string
                          example: Registration
                        question_ko:
                          type: string
                          example: 회원가입은 어떻게 하나요?
                        question_en:
                          type: string
                          example: How do I sign up?
                        answer_ko:
                          type: string
                          example: 회원가입은 이메일을 통해 가능합니다.
                        answer_en:
                          type: string
                          example: You can sign up using your email.
                        manager:
                          type: string
                          example: admin
                        created_by:
                          type: string
                          example: admin
                        updated_by:
                          type: string
                          example: admin
        500:
          description: Error fetching FAQs

  /all_questions:
    get:
      summary: Get all questions
      description: Retrieve a list of all questions with their IDs
      responses:
        200:
          description: A list of questions
          content:
            application/json:
              schema:
                type: object
                properties:
                  questions:
                    type: array
                    items:
                      type: object
                      properties:
                        faq_id:
                          type: number
                          example: 1
                        question_ko:
                          type: string
                          example: 회원가입은 어떻게 하나요?
                        question_en:
                          type: string
                          example: How do I sign up?
        500:
          description: Error fetching questions

  /question:
    post:
      summary: Get FAQs for a question
      description: Returns FAQs based on the provided question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: The question to search FAQs for.
                  example: How do I sign up?
      responses:
        200:
          description: Matching FAQs
          content:
            application/json:
              schema:
                type: object
                properties:
                  faqs:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          example: 1
                        maincategory_ko:
                          type: string
                          example: 일반 질문
                        maincategory_en:
                          type: string
                          example: General Questions
                        subcategory_ko:
                          type: string
                          example: 가입 관련
                        subcategory_en:
                          type: string
                          example: Registration
                        question_ko:
                          type: string
                          example: 회원가입은 어떻게 하나요?
                        question_en:
                          type: string
                          example: How do I sign up?
                        answer_ko:
                          type: string
                          example: 회원가입은 이메일을 통해 가능합니다.
                        answer_en:
                          type: string
                          example: You can sign up using your email.
        400:
          description: Missing required fields
        500:
          description: Error processing the question

  /question_after:
    post:
      summary: Get filtered FAQ answers for a question
      description: Returns a list of FAQ answers filtered and ranked based on the provided question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: The question to get answers for.
                  example: How do I sign up?
      responses:
        200:
          description: Filtered FAQ answers
          content:
            application/json:
              schema:
                type: object
                properties:
                  answersList:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          example: 1
                        question_ko:
                          type: string
                          example: 회원가입은 어떻게 하나요?
                        question_en:
                          type: string
                          example: How do I sign up?
                        answer_ko:
                          type: string
                          example: 회원가입은 이메일을 통해 가능합니다.
                        answer_en:
                          type: string
                          example: You can sign up using your email.
        400:
          description: Missing required fields
        500:
          description: Error processing the question

  /rate:
    post:
      summary: Rate an FAQ
      description: Rate an FAQ by providing its ID and a rate (1 for upvote, -1 for downvote)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                faq_id:
                  type: number
                  description: The ID of the FAQ to rate.
                  example: 1
                rate:
                  type: integer
                  enum: [1, -1]
                  description: The rate value. Use `1` for upvote and `-1` for downvote.
                  example: 1
      responses:
        200:
          description: Successfully rated the FAQ
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        400:
          description: Missing required fields
        500:
          description: Error saving the rating
